spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flightdb
    username: postgres
    password: Password123  # your actual DB password here
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
